/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          primary: 'var(--bg-primary)',
          secondary: 'var(--bg-secondary)',
          tertiary: 'var(--bg-tertiary)',
          elevated: 'var(--bg-elevated)',
          subtle: 'var(--bg-subtle)',
        },
        fg: {
          primary: 'var(--fg-primary)',
          secondary: 'var(--fg-secondary)',
          tertiary: 'var(--fg-tertiary)',
          muted: 'var(--fg-muted)',
          inverse: 'var(--fg-inverse)',
        },
        border: {
          primary: 'var(--border-primary)',
          secondary: 'var(--border-secondary)',
          subtle: 'var(--border-subtle)',
          focus: 'var(--border-focus)',
        },
        accent: {
          primary: 'var(--accent-primary)',
          primaryHover: 'var(--accent-primary-hover)',
          primarySubtle: 'var(--accent-primary-subtle)',
          secondary: 'var(--accent-secondary)',
          secondarySubtle: 'var(--accent-secondary-subtle)',
          success: 'var(--accent-success)',
          successSubtle: 'var(--accent-success-subtle)',
          warning: 'var(--accent-warning)',
          warningSubtle: 'var(--accent-warning-subtle)',
          danger: 'var(--accent-danger)',
          dangerSubtle: 'var(--accent-danger-subtle)',
        },
        brand: {
          blue: '#2563eb',
          blueHover: '#1d4ed8',
          blueLight: 'rgba(37, 99, 235, 0.08)',
          red: '#dc2626',
          redLight: 'rgba(220, 38, 38, 0.08)',
          green: '#059669',
          greenLight: 'rgba(5, 150, 105, 0.08)',
          yellow: '#d97706',
          yellowLight: 'rgba(217, 119, 6, 0.08)',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        display: ['var(--font-display)', 'var(--font-inter)', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        'focus-ring': '0 0 0 3px rgba(37, 99, 235, 0.15)',
        'glow-subtle': '0 0 20px rgba(37, 99, 235, 0.1)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        spring: 'var(--ease-spring)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      animation: {
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'pulse-ring': 'pulse-ring 1.5s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
      },
      backgroundImage: {
        'gradient-subtle': 'linear-gradient(180deg, var(--bg-secondary) 0%, var(--bg-primary) 100%)',
        'gradient-shimmer': 'linear-gradient(90deg, var(--bg-tertiary) 0%, var(--bg-secondary) 50%, var(--bg-tertiary) 100%)',
        'gradient-secti': 'linear-gradient(135deg, #00b5b8 0%, #7c3aed 100%)',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      maxWidth: {
        'prose': '65ch',
        'content': '72rem',
      },
    },
  },
  plugins: [],
}